### ISSUE TITLE
Communication in SCSI mode fails if no serial device is present

### ISSUE THREAD

**Issue by B-G-T** [maehw/snowbirdopter#6]
The command line
`python3 snowbirdopter.py -s /dev/sdb2 -c dump -a 0 -e ff -v9`
fails but the workaround with a serial device
`python3 snowbirdopter.py -s /dev/sg2 -c dump -a 0 -e ff -p /dev/ttyUSB0 -v9`
works.

**Comment by maehw** [comment]
It should be okay now to just provide one device. So know it should be possible to provide a) only a serial device, b) only an SCSI device or c) both a serial and an SCSI device. Exception: commands that use the serial interface always need a serial interface.

Unfortunately I cannot really test b) as my USB/serial converter powers the whole device (so that there's no need to power it by batteries).
